# Generated by Django 4.1.4 on 2022-12-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('answers', models.ManyToManyField(related_name='quiz_answers', to='quiz.option', verbose_name='Answers')),
                ('options', models.ManyToManyField(related_name='quizzes', to='quiz.option', verbose_name='Options')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
