# Generated by Django 4.1.4 on 2022-12-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='quiz_answers', to='quiz.option', verbose_name='Answers'),
        ),
    ]
