# Generated by Django 4.1.4 on 2022-12-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answers',
        ),
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
